import axios from 'axios';

const API_URL = 'http://localhost:5001/api';

const api = axios.create({
  baseURL: API_URL,
});

export const authService = {
  login: async (email) => {
    const response = await api.post('/auth/login', { email });
    return response.data;
  },
  signup: async (name, email, password) => {
    const response = await api.post('/auth/signup', { name, email, password });
    return response.data;
  }
};

export const formService = {
  getMyForms: async (userId) => {
    const response = await api.get(`/forms?userId=${userId}`);
    return response.data;
  },

  getFormById: async (id) => {
    const response = await api.get(`/forms/${id}`);
    return response.data;
  },

  createForm: async (ownerId, title, description) => {
    const response = await api.post('/forms', { ownerId, title, description });
    return response.data;
  },

  updateForm: async (id, updates) => {
    const response = await api.put(`/forms/${id}`, updates);
    return response.data;
  },

  deleteForm: async (id) => {
    await api.delete(`/forms/${id}`);
  },

  // Questions are embedded in Form in MongoDB
  getQuestions: async (formId) => {
    const response = await api.get(`/forms/${formId}`);
    return response.data.questions || [];
  },

  addQuestion: async (formId, type) => {
    // Fetch current form
    const form = await formService.getFormById(formId);
    const questions = form.questions || [];
    
    const newQuestion = {
      // id: generated by Mongo
      type,
      label: 'New Question',
      required: false,
      orderIndex: questions.length,
      options: ['MULTIPLE_CHOICE', 'CHECKBOXES', 'DROPDOWN'].includes(type) ? ['Option 1'] : undefined
    };

    // Update form with new question
    const updatedForm = await formService.updateForm(formId, {
      questions: [...questions, newQuestion]
    });
    
    // Return the newly added question (it will have an _id now)
    return updatedForm.questions[updatedForm.questions.length - 1];
  },

  updateQuestion: async (formId, questionId, updates) => {
    const form = await formService.getFormById(formId);
    const questions = form.questions.map(q => {
      if (q._id === questionId || q.id === questionId) {
        return { ...q, ...updates };
      }
      return q;
    });
    
    const updatedForm = await formService.updateForm(formId, { questions });
    return updatedForm.questions.find(q => q._id === questionId || q.id === questionId);
  },

  deleteQuestion: async (formId, questionId) => {
    const form = await formService.getFormById(formId);
    const questions = form.questions.filter(q => q._id !== questionId && q.id !== questionId);
    await formService.updateForm(formId, { questions });
  },

  submitResponse: async (formId, answers, respondentUserId) => {
    // Transform answers object { questionId: value } to array [{ questionId, value }]
    const answersArray = Object.entries(answers).map(([questionId, value]) => ({
      questionId,
      value
    }));

    const response = await api.post('/responses', {
      formId,
      respondentUserId,
      answers: answersArray
    });
    return response.data;
  },

  getResponses: async (formId) => {
    const response = await api.get(`/responses/${formId}`);
    return response.data;
  },
  
  getFullResponses: async (formId) => {
    // In MongoDB version, responses already contain answers. 
    // We just need to make sure the structure matches what frontend expects.
    const responses = await formService.getResponses(formId);
    return responses;
  }
};
