import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { formService } from '../services/api';
import { geminiService } from '../services/geminiService';
import { Button, Input, Textarea, Card, Modal } from '../components/UI';
import { QuestionType } from '../constants';

const FormBuilder = ({ user, showToast }) => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [form, setForm] = useState(null);
  const [questions, setQuestions] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isAIModalOpen, setIsAIModalOpen] = useState(false);
  const [aiTopic, setAiTopic] = useState('');
  const [isAiLoading, setIsAiLoading] = useState(false);

  useEffect(() => {
    if (id) loadData();
  }, [id]);

  const loadData = async () => {
    try {
      const formData = await formService.getFormById(id);
      const userId = user._id || user.id;
      if (!formData || formData.ownerId !== userId) {
        navigate('/dashboard');
        return;
      }
      // questions are embedded in formData in MERN implementation, 
      // but let's stick to the pattern if api returns them separate or embedded.
      // My api implementation returns form with questions embedded.
      // But getQuestions helper extracts them.
      const questionData = await formService.getQuestions(id);
      setForm(formData);
      setQuestions(questionData);
      setIsLoading(false);
    } catch (e) {
      console.error(e);
      navigate('/dashboard');
    }
  };

  const updateFormTitleDesc = async (updates) => {
    if (!form) return;
    try {
      const formId = form._id || form.id;
      const updated = await formService.updateForm(formId, updates);
      setForm(updated);
    } catch (e) {
      showToast('Failed to update form', 'error');
    }
  };

  const addQuestion = async (type) => {
    if (!form) return;
    try {
      const formId = form._id || form.id;
      const newQ = await formService.addQuestion(formId, type);
      setQuestions(prev => [...prev, newQ]);
      showToast('Question added', 'success');
    } catch (e) {
      showToast('Failed to add question', 'error');
    }
  };

  const updateQuestion = async (qId, updates) => {
    try {
      const formId = form._id || form.id;
      const updated = await formService.updateQuestion(formId, qId, updates);
      setQuestions(prev => prev.map(q => (q._id === qId || q.id === qId) ? updated : q));
    } catch (e) {
      console.error(e);
      showToast('Failed to update question', 'error');
    }
  };

  const deleteQuestion = async (qId) => {
    try {
      const formId = form._id || form.id;
      await formService.deleteQuestion(formId, qId);
      setQuestions(prev => prev.filter(q => q._id !== qId && q.id !== qId));
      showToast('Question removed', 'success');
    } catch (e) {
      showToast('Failed to delete question', 'error');
    }
  };

  const handleAIInvite = async () => {
    setIsAiLoading(true);
    try {
      const details = await geminiService.suggestFormDetails(aiTopic);
      if (details) {
        await updateFormTitleDesc({ title: details.title, description: details.description });
        const suggested = await geminiService.suggestQuestions(details.title, details.description);
        
        // Add questions sequentially
        const formId = form._id || form.id;
        const newQuestions = [];
        for (const q of suggested) {
          const newQ = await formService.addQuestion(formId, q.type);
          const updatedQ = await formService.updateQuestion(formId, newQ._id || newQ.id, { 
            label: q.label, 
            required: q.required, 
            options: q.options 
          });
          newQuestions.push(updatedQ);
        }
        
        // Refresh data to be safe
        await loadData();
        showToast('Form generated by AI!', 'success');
      }
    } catch (e) {
      console.error(e);
      showToast('AI Generation failed', 'error');
    } finally {
      setIsAiLoading(false);
      setIsAIModalOpen(false);
    }
  };

  if (isLoading || !form) return <div className="p-10 text-center">Loading builder...</div>;

  const publicUrl = `${window.location.origin}/f/${form._id || form.id}`;

  return (
    <div className="bg-slate-50 min-h-screen pb-20">
      {/* Top Controls */}
      <div className="bg-white border-b border-slate-200 sticky top-[57px] z-30 px-4 py-2">
        <div className="max-w-4xl mx-auto flex justify-between items-center">
          <div className="flex gap-2">
            <Button variant="secondary" size="sm" onClick={() => navigate('/dashboard')}>Back</Button>
            <Button variant="ghost" size="sm" onClick={() => setIsAIModalOpen(true)} className="text-indigo-600 gap-1">
              ✨ AI Generate
            </Button>
          </div>
          <div className="flex items-center gap-3">
            <span className="text-xs text-slate-400 hidden sm:inline">Saved just now</span>
            <Button 
              variant={form.isPublished ? 'secondary' : 'primary'} 
              size="sm"
              onClick={() => updateFormTitleDesc({ isPublished: !form.isPublished })}
            >
              {form.isPublished ? 'Unpublish' : 'Publish'}
            </Button>
            <Button size="sm" onClick={() => window.open(publicUrl, '_blank')}>
              Preview
            </Button>
          </div>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 mt-8 space-y-6">
        {/* Form Header */}
        <Card className="p-6 border-t-8 border-indigo-600">
          <input 
            className="w-full text-3xl font-bold text-slate-900 border-none focus:ring-0 mb-2"
            value={form.title}
            onChange={e => updateFormTitleDesc({ title: e.target.value })}
            placeholder="Form Title"
          />
          <textarea 
            className="w-full text-slate-600 border-none focus:ring-0 resize-none min-h-[60px]"
            value={form.description}
            onChange={e => updateFormTitleDesc({ description: e.target.value })}
            placeholder="Form description"
          />
        </Card>

        {/* Share Section (if published) */}
        {form.isPublished && (
          <div className="bg-indigo-50 border border-indigo-100 rounded-xl p-4 flex flex-col sm:flex-row items-center gap-4">
            <div className="flex-1">
              <p className="text-sm font-semibold text-indigo-900">Your form is live!</p>
              <p className="text-xs text-indigo-700 truncate">{publicUrl}</p>
            </div>
            <Button size="sm" onClick={() => {
              navigator.clipboard.writeText(publicUrl);
              showToast('Link copied!', 'success');
            }}>Copy Link</Button>
          </div>
        )}

        {/* Questions List */}
        <div className="space-y-4">
          {questions.map((q, idx) => (
            <Card key={q._id || q.id} className="p-6 relative group border-l-4 border-transparent hover:border-indigo-300">
              <div className="flex justify-between items-start mb-4">
                <div className="flex-1 pr-4">
                  <input 
                    className="w-full text-lg font-semibold bg-transparent border-b border-transparent hover:border-slate-200 focus:border-indigo-500 focus:outline-none py-1"
                    value={q.label}
                    onChange={e => updateQuestion(q._id || q.id, { label: e.target.value })}
                    placeholder="Question label"
                  />
                </div>
                <div className="flex items-center gap-3">
                  <select 
                    className="text-xs border rounded p-1 bg-slate-50"
                    value={q.type}
                    onChange={e => updateQuestion(q._id || q.id, { type: e.target.value })}
                  >
                    {Object.values(QuestionType).map(type => (
                      <option key={type} value={type}>{type.replace('_', ' ')}</option>
                    ))}
                  </select>
                  <button onClick={() => deleteQuestion(q._id || q.id)} className="text-slate-300 hover:text-red-500">
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" /></svg>
                  </button>
                </div>
              </div>

              {/* Options for Choice Types */}
              {[QuestionType.MULTIPLE_CHOICE, QuestionType.CHECKBOXES, QuestionType.DROPDOWN].includes(q.type) && (
                <div className="space-y-2 mb-4 pl-4 border-l border-slate-100">
                  {q.options?.map((opt, optIdx) => (
                    <div key={optIdx} className="flex items-center gap-2">
                      <div className={`w-4 h-4 rounded-full border ${q.type === QuestionType.CHECKBOXES ? 'rounded-sm' : ''}`}></div>
                      <input 
                        className="flex-1 text-sm bg-transparent border-none p-0 focus:ring-0"
                        value={opt}
                        onChange={e => {
                          const newOpts = [...(q.options || [])];
                          newOpts[optIdx] = e.target.value;
                          updateQuestion(q._id || q.id, { options: newOpts });
                        }}
                      />
                      <button 
                        onClick={() => {
                          const newOpts = q.options?.filter((_, i) => i !== optIdx);
                          updateQuestion(q._id || q.id, { options: newOpts });
                        }}
                        className="text-slate-300 hover:text-red-400"
                      >
                        ×
                      </button>
                    </div>
                  ))}
                  <button 
                    onClick={() => {
                      const newOpts = [...(q.options || []), `Option ${(q.options?.length || 0) + 1}`];
                      updateQuestion(q._id || q.id, { options: newOpts });
                    }}
                    className="text-sm text-indigo-600 font-medium hover:text-indigo-700 mt-2"
                  >
                    + Add Option
                  </button>
                </div>
              )}

              {/* Footer */}
              <div className="flex items-center gap-4 mt-4 pt-4 border-t border-slate-100">
                <label className="flex items-center gap-2 text-sm text-slate-600 cursor-pointer">
                  <input 
                    type="checkbox"
                    checked={q.required}
                    onChange={e => updateQuestion(q._id || q.id, { required: e.target.checked })}
                    className="rounded text-indigo-600 focus:ring-indigo-500"
                  />
                  Required
                </label>
              </div>
            </Card>
          ))}

          {/* Add Question Button */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
            {[
              { type: QuestionType.SHORT_TEXT, icon: '📝', label: 'Short Text' },
              { type: QuestionType.LONG_TEXT, icon: '📄', label: 'Long Text' },
              { type: QuestionType.MULTIPLE_CHOICE, icon: '◉', label: 'Multiple Choice' },
              { type: QuestionType.CHECKBOXES, icon: '☑', label: 'Checkboxes' },
              { type: QuestionType.DROPDOWN, icon: '▼', label: 'Dropdown' },
              { type: QuestionType.DATE, icon: '📅', label: 'Date' },
              { type: QuestionType.EMAIL, icon: '✉️', label: 'Email' },
              { type: QuestionType.NUMBER, icon: '#', label: 'Number' },
            ].map(item => (
              <button
                key={item.type}
                onClick={() => addQuestion(item.type)}
                className="flex items-center justify-center gap-2 p-3 bg-white border border-slate-200 rounded-lg hover:border-indigo-300 hover:bg-indigo-50 transition-all text-slate-700 hover:text-indigo-700"
              >
                <span>{item.icon}</span>
                <span className="font-medium text-sm">{item.label}</span>
              </button>
            ))}
          </div>
        </div>
      </div>

      <Modal
        isOpen={isAIModalOpen}
        onClose={() => setIsAIModalOpen(false)}
        title="Generate with AI"
      >
        <div className="space-y-4">
          <p className="text-slate-600">Describe the form you want to create, and I'll generate the structure and questions for you.</p>
          <Textarea 
            placeholder="e.g., A customer satisfaction survey for a coffee shop" 
            value={aiTopic}
            onChange={e => setAiTopic(e.target.value)}
          />
          <div className="flex justify-end gap-2">
            <Button variant="ghost" onClick={() => setIsAIModalOpen(false)}>Cancel</Button>
            <Button onClick={handleAIInvite} disabled={!aiTopic || isAiLoading}>
              {isAiLoading ? 'Generating...' : 'Generate Form'}
            </Button>
          </div>
        </div>
      </Modal>
    </div>
  );
};

export default FormBuilder;
